#!/bin/bash
# Download tools helper script

echo "🛠️ ComfyUI Download Tools"
echo "=========================="
echo ""
echo "Available download methods:"
echo ""
echo "2. 📱 Command Line Tools:"
echo ""
echo "   Google Drive:"
echo "   ./download_gdrive.sh 'https://drive.google.com/file/d/ID/view' /workspace/ComfyUI/models/checkpoints/"
echo ""
echo "   HuggingFace:"
echo "   ./download_hf.sh 'runwayml/stable-diffusion-v1-5' 'model.safetensors' /workspace/ComfyUI/models/checkpoints/"
echo ""
echo "   Civitai:"
echo "   ./download_civitai.sh 'https://civitai.com/api/download/models/12345' /workspace/ComfyUI/models/checkpoints/"
echo ""
echo "   Direct URL:"
echo "   wget --show-progress --progress=bar:force -O /workspace/ComfyUI/models/checkpoints/model.safetensors 'https://example.com/model.safetensors'"
echo ""
echo "Model directories:"
echo "  📁 Checkpoints: /workspace/ComfyUI/models/checkpoints/"
echo "  📁 VAE: /workspace/ComfyUI/models/vae/"
echo "  📁 LoRA: /workspace/ComfyUI/models/loras/"
echo "  📁 ControlNet: /workspace/ComfyUI/models/controlnet/"
echo "  📁 Embeddings: /workspace/ComfyUI/models/embeddings/"
echo ""
