#!/bin/bash
# Download tools helper script

echo "🛠️ ComfyUI Download & Workflow Tools"
echo "===================================="
echo ""
echo "📥 Download Methods:"
echo ""
echo "1. Command Line Tools:"
echo ""
echo "   Google Drive:"
echo "   ./download_gdrive.sh 'https://drive.google.com/file/d/ID/view' /workspace/ComfyUI/models/checkpoints/"
echo ""
echo "   HuggingFace:"
echo "   ./download_hf.sh 'runwayml/stable-diffusion-v1-5' 'model.safetensors' /workspace/ComfyUI/models/checkpoints/"
echo ""
echo "   Civitai:"
echo "   ./download_civitai.sh 'https://civitai.com/api/download/models/12345' /workspace/ComfyUI/models/checkpoints/"
echo ""
echo "   Direct URL:"
echo "   wget -O /workspace/ComfyUI/models/checkpoints/model.safetensors 'https://example.com/model.safetensors'"
echo ""
echo "🔄 Workflow Management:"
echo ""
echo "   List workflows:"
echo "   ./workflow_manager.sh list"
echo ""
echo "   Export workflow:"
echo "   ./workflow_manager.sh export"
echo ""
echo "   Import workflow:"
echo "   ./workflow_manager.sh import workflow.json"
echo ""
echo "📁 Model Directories:"
echo "  Checkpoints: /workspace/ComfyUI/models/checkpoints/"
echo "  VAE: /workspace/ComfyUI/models/vae/"
echo "  LoRA: /workspace/ComfyUI/models/loras/"
echo "  ControlNet: /workspace/ComfyUI/models/controlnet/"
echo "  Embeddings: /workspace/ComfyUI/models/embeddings/"
echo "  Workflows: /workspace/workflows/"
echo ""
echo "💡 Workflow Download Options:"
echo "1. Right-click on ComfyUI canvas → 'Save (API Format)'"
echo "2. Use ComfyUI Manager → 'Save Workflow'"
echo "3. Use the Download Workflow button (if available)"
echo ""
